
# This file is automatically generated, you probably don't want to edit this

barchartsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            format = "wide",
            type = "grouped",
            display = FALSE,
            percent = FALSE,
            flip_axes = FALSE,
            sort = FALSE,
            items_title = TRUE,
            items_name = "Survey items",
            freq_title = TRUE,
            showlegend = TRUE,
            palcolor = "RdYlBu",
            imgsizemode = "automaticsize",
            imgwidth = 550,
            imgheight = 300, ...) {

            super$initialize(
                package="nadv",
                name="barcharts",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..format <- jmvcore::OptionList$new(
                "format",
                format,
                options=list(
                    "wide",
                    "long"),
                default="wide")
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "grouped",
                    "stacked",
                    "diverging"),
                default="grouped")
            private$..display <- jmvcore::OptionBool$new(
                "display",
                display,
                default=FALSE)
            private$..percent <- jmvcore::OptionBool$new(
                "percent",
                percent,
                default=FALSE)
            private$..flip_axes <- jmvcore::OptionBool$new(
                "flip_axes",
                flip_axes,
                default=FALSE)
            private$..sort <- jmvcore::OptionBool$new(
                "sort",
                sort,
                default=FALSE)
            private$..items_title <- jmvcore::OptionBool$new(
                "items_title",
                items_title,
                default=TRUE)
            private$..items_name <- jmvcore::OptionString$new(
                "items_name",
                items_name,
                default="Survey items")
            private$..freq_title <- jmvcore::OptionBool$new(
                "freq_title",
                freq_title,
                default=TRUE)
            private$..showlegend <- jmvcore::OptionBool$new(
                "showlegend",
                showlegend,
                default=TRUE)
            private$..palcolor <- jmvcore::OptionList$new(
                "palcolor",
                palcolor,
                options=list(
                    "YlOrRd",
                    "YlOrBr",
                    "YlGnBu",
                    "YlGn",
                    "Reds",
                    "RdPu",
                    "Purples",
                    "PuRd",
                    "PuBuGn",
                    "PuBu",
                    "OrRd",
                    "Oranges",
                    "Greys",
                    "Greens",
                    "GnBu",
                    "BuPu",
                    "BuGn",
                    "Blues",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu"),
                default="RdYlBu")
            private$..imgsizemode <- jmvcore::OptionList$new(
                "imgsizemode",
                imgsizemode,
                options=list(
                    "automaticsize",
                    "customsize"),
                default="automaticsize")
            private$..imgwidth <- jmvcore::OptionInteger$new(
                "imgwidth",
                imgwidth,
                default=550)
            private$..imgheight <- jmvcore::OptionInteger$new(
                "imgheight",
                imgheight,
                default=300)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..format)
            self$.addOption(private$..type)
            self$.addOption(private$..display)
            self$.addOption(private$..percent)
            self$.addOption(private$..flip_axes)
            self$.addOption(private$..sort)
            self$.addOption(private$..items_title)
            self$.addOption(private$..items_name)
            self$.addOption(private$..freq_title)
            self$.addOption(private$..showlegend)
            self$.addOption(private$..palcolor)
            self$.addOption(private$..imgsizemode)
            self$.addOption(private$..imgwidth)
            self$.addOption(private$..imgheight)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        format = function() private$..format$value,
        type = function() private$..type$value,
        display = function() private$..display$value,
        percent = function() private$..percent$value,
        flip_axes = function() private$..flip_axes$value,
        sort = function() private$..sort$value,
        items_title = function() private$..items_title$value,
        items_name = function() private$..items_name$value,
        freq_title = function() private$..freq_title$value,
        showlegend = function() private$..showlegend$value,
        palcolor = function() private$..palcolor$value,
        imgsizemode = function() private$..imgsizemode$value,
        imgwidth = function() private$..imgwidth$value,
        imgheight = function() private$..imgheight$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..format = NA,
        ..type = NA,
        ..display = NA,
        ..percent = NA,
        ..flip_axes = NA,
        ..sort = NA,
        ..items_title = NA,
        ..items_name = NA,
        ..freq_title = NA,
        ..showlegend = NA,
        ..palcolor = NA,
        ..imgsizemode = NA,
        ..imgwidth = NA,
        ..imgheight = NA)
)

barchartsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        barchart = function() private$.items[["barchart"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Charts")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Bar Charts",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="barchart",
                title="Output",
                clearWith=list(
                    "vars",
                    "group",
                    "format",
                    "type",
                    "display",
                    "percent",
                    "flip_axes",
                    "sort",
                    "items_title",
                    "items_name",
                    "freq_title",
                    "showlegend",
                    "palcolor",
                    "imgsizemode",
                    "imgwidth",
                    "imgheight"),
                renderFun=".plot"))}))

barchartsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nadv",
                name = "barcharts",
                version = c(1,0,0),
                options = options,
                results = barchartsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bar Charts
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param format .
#' @param type .
#' @param display .
#' @param percent .
#' @param flip_axes .
#' @param sort .
#' @param items_title .
#' @param items_name .
#' @param freq_title .
#' @param showlegend .
#' @param palcolor .
#' @param imgsizemode .
#' @param imgwidth .
#' @param imgheight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$barchart} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
barcharts <- function(
    data,
    vars,
    group,
    format = "wide",
    type = "grouped",
    display = FALSE,
    percent = FALSE,
    flip_axes = FALSE,
    sort = FALSE,
    items_title = TRUE,
    items_name = "Survey items",
    freq_title = TRUE,
    showlegend = TRUE,
    palcolor = "RdYlBu",
    imgsizemode = "automaticsize",
    imgwidth = 550,
    imgheight = 300) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("barcharts requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barchartsOptions$new(
        vars = vars,
        group = group,
        format = format,
        type = type,
        display = display,
        percent = percent,
        flip_axes = flip_axes,
        sort = sort,
        items_title = items_title,
        items_name = items_name,
        freq_title = freq_title,
        showlegend = showlegend,
        palcolor = palcolor,
        imgsizemode = imgsizemode,
        imgwidth = imgwidth,
        imgheight = imgheight)

    analysis <- barchartsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

