
# This file is automatically generated, you probably don't want to edit this

emotiondetectionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emotiondetectionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sentiment_data = NULL,
            split_var = NULL,
            chart_type = "dodge",
            uncombine = FALSE,
            switch = FALSE,
            disp_by_perc = FALSE,
            horizontal_bars = FALSE,
            palette_colors = "RdYlBu",
            value_labels = FALSE,
            enable_component_axis = TRUE,
            component_axis = "Survey items",
            custom_img_size = FALSE,
            custom_width = 550,
            custom_height = 400, ...) {

            super$initialize(
                package="nadv",
                name="emotiondetection",
                requiresData=TRUE,
                ...)

            private$..sentiment_data <- jmvcore::OptionVariables$new(
                "sentiment_data",
                sentiment_data,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..split_var <- jmvcore::OptionVariable$new(
                "split_var",
                split_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..chart_type <- jmvcore::OptionList$new(
                "chart_type",
                chart_type,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")
            private$..uncombine <- jmvcore::OptionBool$new(
                "uncombine",
                uncombine,
                default=FALSE)
            private$..switch <- jmvcore::OptionBool$new(
                "switch",
                switch,
                default=FALSE)
            private$..disp_by_perc <- jmvcore::OptionBool$new(
                "disp_by_perc",
                disp_by_perc,
                default=FALSE)
            private$..horizontal_bars <- jmvcore::OptionBool$new(
                "horizontal_bars",
                horizontal_bars,
                default=FALSE)
            private$..palette_colors <- jmvcore::OptionList$new(
                "palette_colors",
                palette_colors,
                options=list(
                    "YlOrRd",
                    "YlOrBr",
                    "YlGnBu",
                    "YlGn",
                    "Reds",
                    "RdPu",
                    "Purples",
                    "PuRd",
                    "PuBuGn",
                    "PuBu",
                    "OrRd",
                    "Oranges",
                    "Greys",
                    "Greens",
                    "GnBu",
                    "BuPu",
                    "BuGn",
                    "Blues",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu"),
                default="RdYlBu")
            private$..value_labels <- jmvcore::OptionBool$new(
                "value_labels",
                value_labels,
                default=FALSE)
            private$..enable_component_axis <- jmvcore::OptionBool$new(
                "enable_component_axis",
                enable_component_axis,
                default=TRUE)
            private$..component_axis <- jmvcore::OptionString$new(
                "component_axis",
                component_axis,
                default="Survey items")
            private$..custom_img_size <- jmvcore::OptionBool$new(
                "custom_img_size",
                custom_img_size,
                default=FALSE)
            private$..custom_width <- jmvcore::OptionInteger$new(
                "custom_width",
                custom_width,
                default=550)
            private$..custom_height <- jmvcore::OptionInteger$new(
                "custom_height",
                custom_height,
                default=400)

            self$.addOption(private$..sentiment_data)
            self$.addOption(private$..split_var)
            self$.addOption(private$..chart_type)
            self$.addOption(private$..uncombine)
            self$.addOption(private$..switch)
            self$.addOption(private$..disp_by_perc)
            self$.addOption(private$..horizontal_bars)
            self$.addOption(private$..palette_colors)
            self$.addOption(private$..value_labels)
            self$.addOption(private$..enable_component_axis)
            self$.addOption(private$..component_axis)
            self$.addOption(private$..custom_img_size)
            self$.addOption(private$..custom_width)
            self$.addOption(private$..custom_height)
        }),
    active = list(
        sentiment_data = function() private$..sentiment_data$value,
        split_var = function() private$..split_var$value,
        chart_type = function() private$..chart_type$value,
        uncombine = function() private$..uncombine$value,
        switch = function() private$..switch$value,
        disp_by_perc = function() private$..disp_by_perc$value,
        horizontal_bars = function() private$..horizontal_bars$value,
        palette_colors = function() private$..palette_colors$value,
        value_labels = function() private$..value_labels$value,
        enable_component_axis = function() private$..enable_component_axis$value,
        component_axis = function() private$..component_axis$value,
        custom_img_size = function() private$..custom_img_size$value,
        custom_width = function() private$..custom_width$value,
        custom_height = function() private$..custom_height$value),
    private = list(
        ..sentiment_data = NA,
        ..split_var = NA,
        ..chart_type = NA,
        ..uncombine = NA,
        ..switch = NA,
        ..disp_by_perc = NA,
        ..horizontal_bars = NA,
        ..palette_colors = NA,
        ..value_labels = NA,
        ..enable_component_axis = NA,
        ..component_axis = NA,
        ..custom_img_size = NA,
        ..custom_width = NA,
        ..custom_height = NA)
)

emotiondetectionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emotiondetectionResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Emotion Detection")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                title="Debugging"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Emotion Detection",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                visible=FALSE,
                renderFun=".plot"))}))

emotiondetectionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "emotiondetectionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nadv",
                name = "emotiondetection",
                version = c(1,0,0),
                options = options,
                results = emotiondetectionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Emotion Detection
#'
#' 
#' @param data .
#' @param sentiment_data .
#' @param split_var .
#' @param chart_type .
#' @param uncombine .
#' @param switch .
#' @param disp_by_perc .
#' @param horizontal_bars .
#' @param palette_colors .
#' @param value_labels .
#' @param enable_component_axis .
#' @param component_axis .
#' @param custom_img_size .
#' @param custom_width .
#' @param custom_height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
emotiondetection <- function(
    data,
    sentiment_data,
    split_var,
    chart_type = "dodge",
    uncombine = FALSE,
    switch = FALSE,
    disp_by_perc = FALSE,
    horizontal_bars = FALSE,
    palette_colors = "RdYlBu",
    value_labels = FALSE,
    enable_component_axis = TRUE,
    component_axis = "Survey items",
    custom_img_size = FALSE,
    custom_width = 550,
    custom_height = 400) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("emotiondetection requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sentiment_data)) sentiment_data <- jmvcore::resolveQuo(jmvcore::enquo(sentiment_data))
    if ( ! missing(split_var)) split_var <- jmvcore::resolveQuo(jmvcore::enquo(split_var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sentiment_data), sentiment_data, NULL),
            `if`( ! missing(split_var), split_var, NULL))

    for (v in sentiment_data) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in split_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- emotiondetectionOptions$new(
        sentiment_data = sentiment_data,
        split_var = split_var,
        chart_type = chart_type,
        uncombine = uncombine,
        switch = switch,
        disp_by_perc = disp_by_perc,
        horizontal_bars = horizontal_bars,
        palette_colors = palette_colors,
        value_labels = value_labels,
        enable_component_axis = enable_component_axis,
        component_axis = component_axis,
        custom_img_size = custom_img_size,
        custom_width = custom_width,
        custom_height = custom_height)

    analysis <- emotiondetectionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

