
# This file is automatically generated, you probably don't want to edit this

piechartsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            type = "pie",
            explode = FALSE,
            expvalues = NULL,
            showtitle = TRUE,
            showlabels = FALSE,
            labeltype = "percentage",
            invertcolors = FALSE,
            showlegend = TRUE,
            palcolor = "Purples", ...) {

            super$initialize(
                package="nadv",
                name="piecharts",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pie",
                    "doughnut"),
                default="pie")
            private$..explode <- jmvcore::OptionBool$new(
                "explode",
                explode,
                default=FALSE)
            private$..expvalues <- jmvcore::OptionString$new(
                "expvalues",
                expvalues)
            private$..showtitle <- jmvcore::OptionBool$new(
                "showtitle",
                showtitle,
                default=TRUE)
            private$..showlabels <- jmvcore::OptionBool$new(
                "showlabels",
                showlabels,
                default=FALSE)
            private$..labeltype <- jmvcore::OptionList$new(
                "labeltype",
                labeltype,
                options=list(
                    "percentage",
                    "frequency"),
                default="percentage")
            private$..invertcolors <- jmvcore::OptionBool$new(
                "invertcolors",
                invertcolors,
                default=FALSE)
            private$..showlegend <- jmvcore::OptionBool$new(
                "showlegend",
                showlegend,
                default=TRUE)
            private$..palcolor <- jmvcore::OptionList$new(
                "palcolor",
                palcolor,
                options=list(
                    "YlOrRd",
                    "YlOrBr",
                    "YlGnBu",
                    "YlGn",
                    "Reds",
                    "RdPu",
                    "Purples",
                    "PuRd",
                    "PuBuGn",
                    "PuBu",
                    "OrRd",
                    "Oranges",
                    "Greys",
                    "Greens",
                    "GnBu",
                    "BuPu",
                    "BuGn",
                    "Blues",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu"),
                default="Purples")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..explode)
            self$.addOption(private$..expvalues)
            self$.addOption(private$..showtitle)
            self$.addOption(private$..showlabels)
            self$.addOption(private$..labeltype)
            self$.addOption(private$..invertcolors)
            self$.addOption(private$..showlegend)
            self$.addOption(private$..palcolor)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        explode = function() private$..explode$value,
        expvalues = function() private$..expvalues$value,
        showtitle = function() private$..showtitle$value,
        showlabels = function() private$..showlabels$value,
        labeltype = function() private$..labeltype$value,
        invertcolors = function() private$..invertcolors$value,
        showlegend = function() private$..showlegend$value,
        palcolor = function() private$..palcolor$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..type = NA,
        ..explode = NA,
        ..expvalues = NA,
        ..showtitle = NA,
        ..showlabels = NA,
        ..labeltype = NA,
        ..invertcolors = NA,
        ..showlegend = NA,
        ..palcolor = NA)
)

piechartsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        piecharts = function() private$.items[["piecharts"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pie Charts")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Pie Charts",
                visible=FALSE))
            self$add(jmvcore::Array$new(
                options=options,
                name="piecharts",
                title="Output",
                clearWith=list(
                    "vars",
                    "group",
                    "type",
                    "explode",
                    "expvalues",
                    "showlabels",
                    "labeltype",
                    "showlegend",
                    "palcolor"),
                template=jmvcore::Image$new(
                    options=options,
                    name="$key",
                    renderFun=".plot",
                    clearWith=list())))}))

piechartsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nadv",
                name = "piecharts",
                version = c(1,0,0),
                options = options,
                results = piechartsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Pie Charts
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param type .
#' @param explode .
#' @param expvalues .
#' @param showtitle .
#' @param showlabels .
#' @param labeltype .
#' @param invertcolors .
#' @param showlegend .
#' @param palcolor .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$piecharts} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
piecharts <- function(
    data,
    vars,
    group,
    type = "pie",
    explode = FALSE,
    expvalues,
    showtitle = TRUE,
    showlabels = FALSE,
    labeltype = "percentage",
    invertcolors = FALSE,
    showlegend = TRUE,
    palcolor = "Purples") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("piecharts requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- piechartsOptions$new(
        vars = vars,
        group = group,
        type = type,
        explode = explode,
        expvalues = expvalues,
        showtitle = showtitle,
        showlabels = showlabels,
        labeltype = labeltype,
        invertcolors = invertcolors,
        showlegend = showlegend,
        palcolor = palcolor)

    analysis <- piechartsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

