
# This file is automatically generated, you probably don't want to edit this

sentimenttermsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimenttermsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sentiment_data = NULL,
            split_var = NULL,
            sentiment_type = "all",
            analysis_mode = "aggregate",
            switch = FALSE,
            font_family = "sans",
            font_face = "normal",
            palette_colors = "RdYlBu",
            scale_percentage = 100,
            max_words = 100,
            custom_img_size = FALSE,
            custom_width = 550,
            custom_height = 400, ...) {

            super$initialize(
                package="nadv",
                name="sentimentterms",
                requiresData=TRUE,
                ...)

            private$..sentiment_data <- jmvcore::OptionVariables$new(
                "sentiment_data",
                sentiment_data,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..split_var <- jmvcore::OptionVariable$new(
                "split_var",
                split_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..sentiment_type <- jmvcore::OptionList$new(
                "sentiment_type",
                sentiment_type,
                options=list(
                    "all",
                    "positive",
                    "negative",
                    "anticipation",
                    "trust",
                    "joy",
                    "surprise",
                    "sadness",
                    "anger",
                    "fear",
                    "disgust"),
                default="all")
            private$..analysis_mode <- jmvcore::OptionList$new(
                "analysis_mode",
                analysis_mode,
                options=list(
                    "aggregate",
                    "commonalities",
                    "comparison"),
                default="aggregate")
            private$..switch <- jmvcore::OptionBool$new(
                "switch",
                switch,
                default=FALSE)
            private$..font_family <- jmvcore::OptionList$new(
                "font_family",
                font_family,
                options=list(
                    "sans",
                    "serif",
                    "mono"),
                default="sans")
            private$..font_face <- jmvcore::OptionList$new(
                "font_face",
                font_face,
                options=list(
                    "normal",
                    "bold",
                    "italics",
                    "bold_italics"),
                default="normal")
            private$..palette_colors <- jmvcore::OptionList$new(
                "palette_colors",
                palette_colors,
                options=list(
                    "YlOrRd",
                    "YlOrBr",
                    "YlGnBu",
                    "YlGn",
                    "Reds",
                    "RdPu",
                    "Purples",
                    "PuRd",
                    "PuBuGn",
                    "PuBu",
                    "OrRd",
                    "Oranges",
                    "Greys",
                    "Greens",
                    "GnBu",
                    "BuPu",
                    "BuGn",
                    "Blues",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu"),
                default="RdYlBu")
            private$..scale_percentage <- jmvcore::OptionInteger$new(
                "scale_percentage",
                scale_percentage,
                min=25,
                max=100,
                default=100)
            private$..max_words <- jmvcore::OptionInteger$new(
                "max_words",
                max_words,
                min=10,
                max=1000,
                default=100)
            private$..custom_img_size <- jmvcore::OptionBool$new(
                "custom_img_size",
                custom_img_size,
                default=FALSE)
            private$..custom_width <- jmvcore::OptionInteger$new(
                "custom_width",
                custom_width,
                default=550)
            private$..custom_height <- jmvcore::OptionInteger$new(
                "custom_height",
                custom_height,
                default=400)

            self$.addOption(private$..sentiment_data)
            self$.addOption(private$..split_var)
            self$.addOption(private$..sentiment_type)
            self$.addOption(private$..analysis_mode)
            self$.addOption(private$..switch)
            self$.addOption(private$..font_family)
            self$.addOption(private$..font_face)
            self$.addOption(private$..palette_colors)
            self$.addOption(private$..scale_percentage)
            self$.addOption(private$..max_words)
            self$.addOption(private$..custom_img_size)
            self$.addOption(private$..custom_width)
            self$.addOption(private$..custom_height)
        }),
    active = list(
        sentiment_data = function() private$..sentiment_data$value,
        split_var = function() private$..split_var$value,
        sentiment_type = function() private$..sentiment_type$value,
        analysis_mode = function() private$..analysis_mode$value,
        switch = function() private$..switch$value,
        font_family = function() private$..font_family$value,
        font_face = function() private$..font_face$value,
        palette_colors = function() private$..palette_colors$value,
        scale_percentage = function() private$..scale_percentage$value,
        max_words = function() private$..max_words$value,
        custom_img_size = function() private$..custom_img_size$value,
        custom_width = function() private$..custom_width$value,
        custom_height = function() private$..custom_height$value),
    private = list(
        ..sentiment_data = NA,
        ..split_var = NA,
        ..sentiment_type = NA,
        ..analysis_mode = NA,
        ..switch = NA,
        ..font_family = NA,
        ..font_face = NA,
        ..palette_colors = NA,
        ..scale_percentage = NA,
        ..max_words = NA,
        ..custom_img_size = NA,
        ..custom_width = NA,
        ..custom_height = NA)
)

sentimenttermsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimenttermsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sentiment Terms")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Sentiment Terms",
                visible=FALSE))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Wordclouds",
                visible=FALSE,
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".plot")))}))

sentimenttermsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimenttermsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nadv",
                name = "sentimentterms",
                version = c(1,0,0),
                options = options,
                results = sentimenttermsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Sentiment Terms
#'
#' 
#' @param data .
#' @param sentiment_data .
#' @param split_var .
#' @param sentiment_type .
#' @param analysis_mode .
#' @param switch .
#' @param font_family .
#' @param font_face .
#' @param palette_colors .
#' @param scale_percentage .
#' @param max_words .
#' @param custom_img_size .
#' @param custom_width .
#' @param custom_height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
sentimentterms <- function(
    data,
    sentiment_data,
    split_var,
    sentiment_type = "all",
    analysis_mode = "aggregate",
    switch = FALSE,
    font_family = "sans",
    font_face = "normal",
    palette_colors = "RdYlBu",
    scale_percentage = 100,
    max_words = 100,
    custom_img_size = FALSE,
    custom_width = 550,
    custom_height = 400) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("sentimentterms requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sentiment_data)) sentiment_data <- jmvcore::resolveQuo(jmvcore::enquo(sentiment_data))
    if ( ! missing(split_var)) split_var <- jmvcore::resolveQuo(jmvcore::enquo(split_var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sentiment_data), sentiment_data, NULL),
            `if`( ! missing(split_var), split_var, NULL))

    for (v in sentiment_data) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in split_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- sentimenttermsOptions$new(
        sentiment_data = sentiment_data,
        split_var = split_var,
        sentiment_type = sentiment_type,
        analysis_mode = analysis_mode,
        switch = switch,
        font_family = font_family,
        font_face = font_face,
        palette_colors = palette_colors,
        scale_percentage = scale_percentage,
        max_words = max_words,
        custom_img_size = custom_img_size,
        custom_width = custom_width,
        custom_height = custom_height)

    analysis <- sentimenttermsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

