
# This file is automatically generated, you probably don't want to edit this

sentimentscoresOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimentscoresOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sentiment_data = NULL,
            iv = NULL,
            chart_type = NULL,
            scoring_method = "by_sentence",
            averaging_method = "default_averaging",
            uncombine = FALSE,
            split_by_iv = FALSE,
            facet_mode = FALSE,
            add_graphics = FALSE,
            custom_img_size = FALSE,
            custom_width = 550,
            custom_height = 300,
            palette_colors = NULL, ...) {

            super$initialize(
                package="nadv",
                name="sentimentscores",
                requiresData=TRUE,
                ...)

            private$..sentiment_data <- jmvcore::OptionVariables$new(
                "sentiment_data",
                sentiment_data,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..iv <- jmvcore::OptionVariable$new(
                "iv",
                iv,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..chart_type <- jmvcore::OptionList$new(
                "chart_type",
                chart_type,
                options=list(
                    "ct_boxplots",
                    "ct_density",
                    "ct_scatterplots"))
            private$..scoring_method <- jmvcore::OptionList$new(
                "scoring_method",
                scoring_method,
                options=list(
                    "by_sentence",
                    "by_cell",
                    "by_row"),
                default="by_sentence")
            private$..averaging_method <- jmvcore::OptionList$new(
                "averaging_method",
                averaging_method,
                options=list(
                    "default_averaging",
                    "courtesy_reduction",
                    "neutrality_reduction"),
                default="default_averaging")
            private$..uncombine <- jmvcore::OptionBool$new(
                "uncombine",
                uncombine,
                default=FALSE)
            private$..split_by_iv <- jmvcore::OptionBool$new(
                "split_by_iv",
                split_by_iv,
                default=FALSE)
            private$..facet_mode <- jmvcore::OptionBool$new(
                "facet_mode",
                facet_mode,
                default=FALSE)
            private$..add_graphics <- jmvcore::OptionBool$new(
                "add_graphics",
                add_graphics,
                default=FALSE)
            private$..custom_img_size <- jmvcore::OptionBool$new(
                "custom_img_size",
                custom_img_size,
                default=FALSE)
            private$..custom_width <- jmvcore::OptionInteger$new(
                "custom_width",
                custom_width,
                default=550)
            private$..custom_height <- jmvcore::OptionInteger$new(
                "custom_height",
                custom_height,
                default=300)
            private$..palette_colors <- jmvcore::OptionList$new(
                "palette_colors",
                palette_colors,
                options=list(
                    "YlOrRd",
                    "YlOrBr",
                    "YlGnBu",
                    "YlGn",
                    "Reds",
                    "RdPu",
                    "Purples",
                    "PuRd",
                    "PuBuGn",
                    "PuBu",
                    "OrRd",
                    "Oranges",
                    "Greys",
                    "Greens",
                    "GnBu",
                    "BuPu",
                    "BuGn",
                    "Blues",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu"))

            self$.addOption(private$..sentiment_data)
            self$.addOption(private$..iv)
            self$.addOption(private$..chart_type)
            self$.addOption(private$..scoring_method)
            self$.addOption(private$..averaging_method)
            self$.addOption(private$..uncombine)
            self$.addOption(private$..split_by_iv)
            self$.addOption(private$..facet_mode)
            self$.addOption(private$..add_graphics)
            self$.addOption(private$..custom_img_size)
            self$.addOption(private$..custom_width)
            self$.addOption(private$..custom_height)
            self$.addOption(private$..palette_colors)
        }),
    active = list(
        sentiment_data = function() private$..sentiment_data$value,
        iv = function() private$..iv$value,
        chart_type = function() private$..chart_type$value,
        scoring_method = function() private$..scoring_method$value,
        averaging_method = function() private$..averaging_method$value,
        uncombine = function() private$..uncombine$value,
        split_by_iv = function() private$..split_by_iv$value,
        facet_mode = function() private$..facet_mode$value,
        add_graphics = function() private$..add_graphics$value,
        custom_img_size = function() private$..custom_img_size$value,
        custom_width = function() private$..custom_width$value,
        custom_height = function() private$..custom_height$value,
        palette_colors = function() private$..palette_colors$value),
    private = list(
        ..sentiment_data = NA,
        ..iv = NA,
        ..chart_type = NA,
        ..scoring_method = NA,
        ..averaging_method = NA,
        ..uncombine = NA,
        ..split_by_iv = NA,
        ..facet_mode = NA,
        ..add_graphics = NA,
        ..custom_img_size = NA,
        ..custom_width = NA,
        ..custom_height = NA,
        ..palette_colors = NA)
)

sentimentscoresResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimentscoresResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sentiment Scores")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Sentiment Analysis",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                visible=FALSE,
                renderFun=".plot"))}))

sentimentscoresBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sentimentscoresBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nadv",
                name = "sentimentscores",
                version = c(1,0,0),
                options = options,
                results = sentimentscoresResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Sentiment Scores
#'
#' 
#' @param data .
#' @param sentiment_data .
#' @param iv .
#' @param chart_type .
#' @param scoring_method .
#' @param averaging_method .
#' @param uncombine .
#' @param split_by_iv .
#' @param facet_mode .
#' @param add_graphics .
#' @param custom_img_size .
#' @param custom_width .
#' @param custom_height .
#' @param palette_colors .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
sentimentscores <- function(
    data,
    sentiment_data,
    iv,
    chart_type,
    scoring_method = "by_sentence",
    averaging_method = "default_averaging",
    uncombine = FALSE,
    split_by_iv = FALSE,
    facet_mode = FALSE,
    add_graphics = FALSE,
    custom_img_size = FALSE,
    custom_width = 550,
    custom_height = 300,
    palette_colors) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("sentimentscores requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sentiment_data)) sentiment_data <- jmvcore::resolveQuo(jmvcore::enquo(sentiment_data))
    if ( ! missing(iv)) iv <- jmvcore::resolveQuo(jmvcore::enquo(iv))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sentiment_data), sentiment_data, NULL),
            `if`( ! missing(iv), iv, NULL))

    for (v in sentiment_data) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- sentimentscoresOptions$new(
        sentiment_data = sentiment_data,
        iv = iv,
        chart_type = chart_type,
        scoring_method = scoring_method,
        averaging_method = averaging_method,
        uncombine = uncombine,
        split_by_iv = split_by_iv,
        facet_mode = facet_mode,
        add_graphics = add_graphics,
        custom_img_size = custom_img_size,
        custom_width = custom_width,
        custom_height = custom_height,
        palette_colors = palette_colors)

    analysis <- sentimentscoresClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

